START TRANSACTION;

ALTER TABLE clients
ADD COLUMN public_id UUID NOT NULL DEFAULT UUID(),
ADD COLUMN createdAt DATE NOT NULL DEFAULT CURRENT_TIMESTAMP(),
ADD COLUMN lastContact DATE,
ADD COLUMN nextFollowup DATE,
ADD UNIQUE KEY (public_id);

UPDATE clients 
SET createdAt = created;

COMMIT;
